//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type DeptEmp struct {
	EmpNo    int32  `sql:"primary_key"`
	DeptNo   string `sql:"primary_key"`
	FromDate time.Time
	ToDate   time.Time
}
