//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Division struct {
	ID        int64 `sql:"primary_key"`
	Name      string
	IsDeleted bool
	CreatedAt time.Time
	UpdatedAt *time.Time
	DeletedAt *time.Time
}
