//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type EmployeesGender string

const (
	EmployeesGender_M EmployeesGender = "M"
	EmployeesGender_F EmployeesGender = "F"
)

func (e *EmployeesGender) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "M":
		*e = EmployeesGender_M
	case "F":
		*e = EmployeesGender_F
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for EmployeesGender enum")
	}

	return nil
}

func (e EmployeesGender) String() string {
	return string(e)
}
