//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Employees struct {
	EmpNo     int32 `sql:"primary_key"`
	BirthDate time.Time
	FirstName string
	LastName  string
	Gender    EmployeesGender
	HireDate  time.Time
}
