//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var DeptManager = newDeptManagerTable("go-blog", "dept_manager", "")

type deptManagerTable struct {
	mysql.Table

	// Columns
	EmpNo    mysql.ColumnInteger
	DeptNo   mysql.ColumnString
	FromDate mysql.ColumnDate
	ToDate   mysql.ColumnDate

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type DeptManagerTable struct {
	deptManagerTable

	NEW deptManagerTable
}

// AS creates new DeptManagerTable with assigned alias
func (a DeptManagerTable) AS(alias string) *DeptManagerTable {
	return newDeptManagerTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new DeptManagerTable with assigned schema name
func (a DeptManagerTable) FromSchema(schemaName string) *DeptManagerTable {
	return newDeptManagerTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new DeptManagerTable with assigned table prefix
func (a DeptManagerTable) WithPrefix(prefix string) *DeptManagerTable {
	return newDeptManagerTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new DeptManagerTable with assigned table suffix
func (a DeptManagerTable) WithSuffix(suffix string) *DeptManagerTable {
	return newDeptManagerTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newDeptManagerTable(schemaName, tableName, alias string) *DeptManagerTable {
	return &DeptManagerTable{
		deptManagerTable: newDeptManagerTableImpl(schemaName, tableName, alias),
		NEW:              newDeptManagerTableImpl("", "new", ""),
	}
}

func newDeptManagerTableImpl(schemaName, tableName, alias string) deptManagerTable {
	var (
		EmpNoColumn    = mysql.IntegerColumn("emp_no")
		DeptNoColumn   = mysql.StringColumn("dept_no")
		FromDateColumn = mysql.DateColumn("from_date")
		ToDateColumn   = mysql.DateColumn("to_date")
		allColumns     = mysql.ColumnList{EmpNoColumn, DeptNoColumn, FromDateColumn, ToDateColumn}
		mutableColumns = mysql.ColumnList{FromDateColumn, ToDateColumn}
	)

	return deptManagerTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		EmpNo:    EmpNoColumn,
		DeptNo:   DeptNoColumn,
		FromDate: FromDateColumn,
		ToDate:   ToDateColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
