//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Salaries = newSalariesTable("go-blog", "salaries", "")

type salariesTable struct {
	mysql.Table

	// Columns
	EmpNo    mysql.ColumnInteger
	Salary   mysql.ColumnInteger
	FromDate mysql.ColumnDate
	ToDate   mysql.ColumnDate

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type SalariesTable struct {
	salariesTable

	NEW salariesTable
}

// AS creates new SalariesTable with assigned alias
func (a SalariesTable) AS(alias string) *SalariesTable {
	return newSalariesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SalariesTable with assigned schema name
func (a SalariesTable) FromSchema(schemaName string) *SalariesTable {
	return newSalariesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SalariesTable with assigned table prefix
func (a SalariesTable) WithPrefix(prefix string) *SalariesTable {
	return newSalariesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SalariesTable with assigned table suffix
func (a SalariesTable) WithSuffix(suffix string) *SalariesTable {
	return newSalariesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSalariesTable(schemaName, tableName, alias string) *SalariesTable {
	return &SalariesTable{
		salariesTable: newSalariesTableImpl(schemaName, tableName, alias),
		NEW:           newSalariesTableImpl("", "new", ""),
	}
}

func newSalariesTableImpl(schemaName, tableName, alias string) salariesTable {
	var (
		EmpNoColumn    = mysql.IntegerColumn("emp_no")
		SalaryColumn   = mysql.IntegerColumn("salary")
		FromDateColumn = mysql.DateColumn("from_date")
		ToDateColumn   = mysql.DateColumn("to_date")
		allColumns     = mysql.ColumnList{EmpNoColumn, SalaryColumn, FromDateColumn, ToDateColumn}
		mutableColumns = mysql.ColumnList{SalaryColumn, ToDateColumn}
	)

	return salariesTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		EmpNo:    EmpNoColumn,
		Salary:   SalaryColumn,
		FromDate: FromDateColumn,
		ToDate:   ToDateColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
