//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Titles = newTitlesTable("go-blog", "titles", "")

type titlesTable struct {
	mysql.Table

	// Columns
	EmpNo    mysql.ColumnInteger
	Title    mysql.ColumnString
	FromDate mysql.ColumnDate
	ToDate   mysql.ColumnDate

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type TitlesTable struct {
	titlesTable

	NEW titlesTable
}

// AS creates new TitlesTable with assigned alias
func (a TitlesTable) AS(alias string) *TitlesTable {
	return newTitlesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TitlesTable with assigned schema name
func (a TitlesTable) FromSchema(schemaName string) *TitlesTable {
	return newTitlesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TitlesTable with assigned table prefix
func (a TitlesTable) WithPrefix(prefix string) *TitlesTable {
	return newTitlesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TitlesTable with assigned table suffix
func (a TitlesTable) WithSuffix(suffix string) *TitlesTable {
	return newTitlesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTitlesTable(schemaName, tableName, alias string) *TitlesTable {
	return &TitlesTable{
		titlesTable: newTitlesTableImpl(schemaName, tableName, alias),
		NEW:         newTitlesTableImpl("", "new", ""),
	}
}

func newTitlesTableImpl(schemaName, tableName, alias string) titlesTable {
	var (
		EmpNoColumn    = mysql.IntegerColumn("emp_no")
		TitleColumn    = mysql.StringColumn("title")
		FromDateColumn = mysql.DateColumn("from_date")
		ToDateColumn   = mysql.DateColumn("to_date")
		allColumns     = mysql.ColumnList{EmpNoColumn, TitleColumn, FromDateColumn, ToDateColumn}
		mutableColumns = mysql.ColumnList{ToDateColumn}
	)

	return titlesTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		EmpNo:    EmpNoColumn,
		Title:    TitleColumn,
		FromDate: FromDateColumn,
		ToDate:   ToDateColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
